# Generated by Django 5.2 on 2025-05-05 05:22

from django.db import migrations

def criar_dias(apps, schema_editor):
    Dia = apps.get_model('alunos', 'Dia')
    for i in range(1, 32):
        Dia.objects.get_or_create(dia=i)

def reverter_dias(apps, schema_editor):
    Dia = apps.get_model('alunos', 'Dia')
    Dia.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),  # Substitua pelo nome da sua migração anterior
    ]

    operations = [
        migrations.RunPython(criar_dias, reverter_dias),
    ]
