# Generated by Django 5.2 on 2025-05-06 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_aluno_preço'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dia_vencimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alunos.dia'),
        ),
    ]
